### ISSUE TITLE
Item.Context.DetailUrl Not Always Working

### ISSUE THREAD

**Issue by mikesmeltzer** [sachatrauwaen/DNN_OpenContentProvider#1]
The URL that is generated via open content when using Item.Context.DetailUrl is not always giving the URL as defined within the manifest.

For example, sometimes the URL in  Item.Context.DetailUrl will be exactly as it should based on the manifest and other times it will have the item ID in it, etc.

Is there a specific order of operations or settings that need to be set in order for the  Item.Context.DetailUrl to always show the proper URL as defined with the manifest?

The actual page, if I manually go to it with the nicer URL does work but I cannot hardcode my links and need to rely on the Item.Context.DetailUrl.

Note:  I'm trying to use this functionality in combination with using the source of data as another Open Content module from another page. For example, I have a blog management page that is my main source of data for other Open Content modules on other pages.  Those other pages I want to use as my detail page with the nicer URL's as defined in the manifest.

**Comment by sachatrauwaen** [comment]
No there no real raison that urls are nor rewriten.

The only think i already see, is thet the cash is ut sink, for exemple when you change manifest after entering the content.

You can clear  the url cach in the global settings.

Let me know if that solve your issue.

**Comment by mikesmeltzer** [comment]
@sachatrauwaen Okay, thanks, clearing the cache via the global settings has fixed the urls.

Without doing this manually, when would OpentContent clear it's URL cache?

**Comment by sachatrauwaen** [comment]
Opencontent  update the url cache when opencontent add, update and delete content.


The cache is not automatically cleared when settings, schema or manifest are updated.

**Comment by mikesmeltzer** [comment]
Sacha,

This is now working consistently for me and appears was a local caching issue.

I'll go ahead and close this issue.

Thanks!

Mike
